version: '3.3'

services:
  dbMysql:
    ports:
      - "3306:3306"

  php:
    ports:
      - 8000:8000
    volumes:
      - ./projeto_portfolio:/var/www/html

  phpmyadmin:
    ports:
       - 8081:80