version: '3.3'

services:
  dbMysql:
    ports:
      - "3306:3306"

  php:
    ports:
      - 8000:8000
    # volumes:
    #   - ./projeto_portfolio:/var/www/html
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './projeto_portfolio:/app'

  phpmyadmin:
    ports:
       - 8081:80