version: '3.3'
services:
  dbMysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portifolio

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    links:
      - dbMysql:dbMysql
  
  php:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    volumes:
      - './projeto_portfolio:/app'
   